import type { Book, Quote, LibraryEntry } from "./types";

/**
 * Persistence-agnostic library API.
 *
 * Both the IndexedDB implementation (guest mode) and the Supabase
 * implementation (signed-in) satisfy this contract — letting the UI
 * swap stores by auth state without knowing which is active.
 *
 * See `docs/superpowers/specs/2026-05-12-bookshelf-design.md` §2.2.
 */
export interface LibraryStorage {
  // ─── Library entries (the user's shelf ordering) ──────────────────
  listLibrary(): Promise<LibraryEntry[]>;
  /**
   * Adds `book` to the library. If the book is already present, the
   * existing entry is returned and `position` is preserved.
   */
  addToLibrary(book: Book): Promise<LibraryEntry>;
  removeFromLibrary(isbn: string): Promise<void>;

  // ─── Books (canonical metadata, keyed by ISBN) ────────────────────
  getBook(isbn: string): Promise<Book | null>;
  upsertBook(book: Book): Promise<void>;

  // ─── Quotes (passages saved from a specific book) ─────────────────
  listQuotes(bookIsbn: string): Promise<Quote[]>;
  /**
   * Inserts a new quote. `id` (uuid) and `createdAt` (ISO 8601) are
   * generated by the implementation.
   */
  addQuote(input: Omit<Quote, "id" | "createdAt">): Promise<Quote>;
  deleteQuote(id: string): Promise<void>;
}
